version: 2.0
jobs:
    
    "all-jupyter-py36-cu90_all-jupyter-py36_all-jupyter":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:all-jupyter-py36-cu90 -t $DOCKER_REPO:all-jupyter-py36 -t $DOCKER_REPO:all-jupyter -f docker/Dockerfile.all-jupyter-py36-cu90 .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:all-jupyter-py36-cu90            
            - run: docker push $DOCKER_REPO:all-jupyter-py36            
            - run: docker push $DOCKER_REPO:all-jupyter
    
    "mxnet-py36-cpu_mxnet-cpu":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:mxnet-py36-cpu -t $DOCKER_REPO:mxnet-cpu -f docker/Dockerfile.mxnet-py36-cpu .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:mxnet-py36-cpu            
            - run: docker push $DOCKER_REPO:mxnet-cpu
    
    "tensorflow-py36-cpu_tensorflow-cpu":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:tensorflow-py36-cpu -t $DOCKER_REPO:tensorflow-cpu -f docker/Dockerfile.tensorflow-py36-cpu .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:tensorflow-py36-cpu            
            - run: docker push $DOCKER_REPO:tensorflow-cpu
    
    "cntk-py36-cu90_cntk-py36_cntk":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:cntk-py36-cu90 -t $DOCKER_REPO:cntk-py36 -t $DOCKER_REPO:cntk -f docker/Dockerfile.cntk-py36-cu90 .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:cntk-py36-cu90            
            - run: docker push $DOCKER_REPO:cntk-py36            
            - run: docker push $DOCKER_REPO:cntk
    
    "sonnet-py36-cpu_sonnet-cpu":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:sonnet-py36-cpu -t $DOCKER_REPO:sonnet-cpu -f docker/Dockerfile.sonnet-py36-cpu .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:sonnet-py36-cpu            
            - run: docker push $DOCKER_REPO:sonnet-cpu
    
    "darknet-cu90_darknet":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:darknet-cu90 -t $DOCKER_REPO:darknet -f docker/Dockerfile.darknet-cu90 .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:darknet-cu90            
            - run: docker push $DOCKER_REPO:darknet
    
    "keras-py36-cu90_keras-py36_keras":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:keras-py36-cu90 -t $DOCKER_REPO:keras-py36 -t $DOCKER_REPO:keras -f docker/Dockerfile.keras-py36-cu90 .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:keras-py36-cu90            
            - run: docker push $DOCKER_REPO:keras-py36            
            - run: docker push $DOCKER_REPO:keras
    
    "all-py36-cpu_all-cpu_py36-cpu_cpu":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:all-py36-cpu -t $DOCKER_REPO:all-cpu -t $DOCKER_REPO:py36-cpu -t $DOCKER_REPO:cpu -f docker/Dockerfile.all-py36-cpu .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:all-py36-cpu            
            - run: docker push $DOCKER_REPO:all-cpu            
            - run: docker push $DOCKER_REPO:py36-cpu            
            - run: docker push $DOCKER_REPO:cpu
    
    "caffe-py36-cu90_caffe-py36_caffe":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:caffe-py36-cu90 -t $DOCKER_REPO:caffe-py36 -t $DOCKER_REPO:caffe -f docker/Dockerfile.caffe-py36-cu90 .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:caffe-py36-cu90            
            - run: docker push $DOCKER_REPO:caffe-py36            
            - run: docker push $DOCKER_REPO:caffe
    
    "darknet-cpu":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:darknet-cpu -f docker/Dockerfile.darknet-cpu .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:darknet-cpu
    
    "lasagne-py36-cpu_lasagne-cpu":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:lasagne-py36-cpu -t $DOCKER_REPO:lasagne-cpu -f docker/Dockerfile.lasagne-py36-cpu .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:lasagne-py36-cpu            
            - run: docker push $DOCKER_REPO:lasagne-cpu
    
    "chainer-py36-cu90_chainer-py36_chainer":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:chainer-py36-cu90 -t $DOCKER_REPO:chainer-py36 -t $DOCKER_REPO:chainer -f docker/Dockerfile.chainer-py36-cu90 .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:chainer-py36-cu90            
            - run: docker push $DOCKER_REPO:chainer-py36            
            - run: docker push $DOCKER_REPO:chainer
    
    "keras-py36-cpu_keras-cpu":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:keras-py36-cpu -t $DOCKER_REPO:keras-cpu -f docker/Dockerfile.keras-py36-cpu .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:keras-py36-cpu            
            - run: docker push $DOCKER_REPO:keras-cpu
    
    "theano-py36-cpu_theano-cpu":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:theano-py36-cpu -t $DOCKER_REPO:theano-cpu -f docker/Dockerfile.theano-py36-cpu .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:theano-py36-cpu            
            - run: docker push $DOCKER_REPO:theano-cpu
    
    "sonnet-py36-cu90_sonnet-py36_sonnet":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:sonnet-py36-cu90 -t $DOCKER_REPO:sonnet-py36 -t $DOCKER_REPO:sonnet -f docker/Dockerfile.sonnet-py36-cu90 .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:sonnet-py36-cu90            
            - run: docker push $DOCKER_REPO:sonnet-py36            
            - run: docker push $DOCKER_REPO:sonnet
    
    "mxnet-py36-cu90_mxnet-py36_mxnet":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:mxnet-py36-cu90 -t $DOCKER_REPO:mxnet-py36 -t $DOCKER_REPO:mxnet -f docker/Dockerfile.mxnet-py36-cu90 .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:mxnet-py36-cu90            
            - run: docker push $DOCKER_REPO:mxnet-py36            
            - run: docker push $DOCKER_REPO:mxnet
    
    "chainer-py36-cpu_chainer-cpu":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:chainer-py36-cpu -t $DOCKER_REPO:chainer-cpu -f docker/Dockerfile.chainer-py36-cpu .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:chainer-py36-cpu            
            - run: docker push $DOCKER_REPO:chainer-cpu
    
    "all-jupyter-py36-cpu_all-jupyter-cpu":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:all-jupyter-py36-cpu -t $DOCKER_REPO:all-jupyter-cpu -f docker/Dockerfile.all-jupyter-py36-cpu .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:all-jupyter-py36-cpu            
            - run: docker push $DOCKER_REPO:all-jupyter-cpu
    
    "torch-cpu":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:torch-cpu -f docker/Dockerfile.torch-cpu .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:torch-cpu
    
    "cntk-py36-cpu_cntk-cpu":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:cntk-py36-cpu -t $DOCKER_REPO:cntk-cpu -f docker/Dockerfile.cntk-py36-cpu .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:cntk-py36-cpu            
            - run: docker push $DOCKER_REPO:cntk-cpu
    
    "caffe2-py36-cpu_caffe2-cpu":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:caffe2-py36-cpu -t $DOCKER_REPO:caffe2-cpu -f docker/Dockerfile.caffe2-py36-cpu .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:caffe2-py36-cpu            
            - run: docker push $DOCKER_REPO:caffe2-cpu
    
    "pytorch-py36-cu90_pytorch-py36_pytorch":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:pytorch-py36-cu90 -t $DOCKER_REPO:pytorch-py36 -t $DOCKER_REPO:pytorch -f docker/Dockerfile.pytorch-py36-cu90 .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:pytorch-py36-cu90            
            - run: docker push $DOCKER_REPO:pytorch-py36            
            - run: docker push $DOCKER_REPO:pytorch
    
    "lasagne-py36-cu90_lasagne-py36_lasagne":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:lasagne-py36-cu90 -t $DOCKER_REPO:lasagne-py36 -t $DOCKER_REPO:lasagne -f docker/Dockerfile.lasagne-py36-cu90 .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:lasagne-py36-cu90            
            - run: docker push $DOCKER_REPO:lasagne-py36            
            - run: docker push $DOCKER_REPO:lasagne
    
    "theano-py36-cu90_theano-py36_theano":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:theano-py36-cu90 -t $DOCKER_REPO:theano-py36 -t $DOCKER_REPO:theano -f docker/Dockerfile.theano-py36-cu90 .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:theano-py36-cu90            
            - run: docker push $DOCKER_REPO:theano-py36            
            - run: docker push $DOCKER_REPO:theano
    
    "torch-cu90_torch":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:torch-cu90 -t $DOCKER_REPO:torch -f docker/Dockerfile.torch-cu90 .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:torch-cu90            
            - run: docker push $DOCKER_REPO:torch
    
    "all-py36-cu90_all-py36_all_py36-cu90_latest":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:all-py36-cu90 -t $DOCKER_REPO:all-py36 -t $DOCKER_REPO:all -t $DOCKER_REPO:py36-cu90 -t $DOCKER_REPO:latest -f docker/Dockerfile.all-py36-cu90 .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:all-py36-cu90            
            - run: docker push $DOCKER_REPO:all-py36            
            - run: docker push $DOCKER_REPO:all            
            - run: docker push $DOCKER_REPO:py36-cu90            
            - run: docker push $DOCKER_REPO:latest
    
    "tensorflow-py36-cu90_tensorflow-py36_tensorflow":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:tensorflow-py36-cu90 -t $DOCKER_REPO:tensorflow-py36 -t $DOCKER_REPO:tensorflow -f docker/Dockerfile.tensorflow-py36-cu90 .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:tensorflow-py36-cu90            
            - run: docker push $DOCKER_REPO:tensorflow-py36            
            - run: docker push $DOCKER_REPO:tensorflow
    
    "pytorch-py36-cpu_pytorch-cpu":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:pytorch-py36-cpu -t $DOCKER_REPO:pytorch-cpu -f docker/Dockerfile.pytorch-py36-cpu .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:pytorch-py36-cpu            
            - run: docker push $DOCKER_REPO:pytorch-cpu
    
    "caffe-py36-cpu_caffe-cpu":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:caffe-py36-cpu -t $DOCKER_REPO:caffe-cpu -f docker/Dockerfile.caffe-py36-cpu .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:caffe-py36-cpu            
            - run: docker push $DOCKER_REPO:caffe-cpu
    
    "caffe2-py36-cu90_caffe2-py36_caffe2":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:caffe2-py36-cu90 -t $DOCKER_REPO:caffe2-py36 -t $DOCKER_REPO:caffe2 -f docker/Dockerfile.caffe2-py36-cu90 .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:caffe2-py36-cu90            
            - run: docker push $DOCKER_REPO:caffe2-py36            
            - run: docker push $DOCKER_REPO:caffe2

workflows:
    version: 2
    build:
        jobs:
            - "all-jupyter-py36-cu90_all-jupyter-py36_all-jupyter"
            - "mxnet-py36-cpu_mxnet-cpu"
            - "tensorflow-py36-cpu_tensorflow-cpu"
            - "cntk-py36-cu90_cntk-py36_cntk"
            - "sonnet-py36-cpu_sonnet-cpu"
            - "darknet-cu90_darknet"
            - "keras-py36-cu90_keras-py36_keras"
            - "all-py36-cpu_all-cpu_py36-cpu_cpu"
            - "caffe-py36-cu90_caffe-py36_caffe"
            - "darknet-cpu"
            - "lasagne-py36-cpu_lasagne-cpu"
            - "chainer-py36-cu90_chainer-py36_chainer"
            - "keras-py36-cpu_keras-cpu"
            - "theano-py36-cpu_theano-cpu"
            - "sonnet-py36-cu90_sonnet-py36_sonnet"
            - "mxnet-py36-cu90_mxnet-py36_mxnet"
            - "chainer-py36-cpu_chainer-cpu"
            - "all-jupyter-py36-cpu_all-jupyter-cpu"
            - "torch-cpu"
            - "cntk-py36-cpu_cntk-cpu"
            - "caffe2-py36-cpu_caffe2-cpu"
            - "pytorch-py36-cu90_pytorch-py36_pytorch"
            - "lasagne-py36-cu90_lasagne-py36_lasagne"
            - "theano-py36-cu90_theano-py36_theano"
            - "torch-cu90_torch"
            - "all-py36-cu90_all-py36_all_py36-cu90_latest"
            - "tensorflow-py36-cu90_tensorflow-py36_tensorflow"
            - "pytorch-py36-cpu_pytorch-cpu"
            - "caffe-py36-cpu_caffe-cpu"
            - "caffe2-py36-cu90_caffe2-py36_caffe2"